### PR TITLE
Stringify JSON-LD

### LINKED ISSUE #89: Stop hand-rendering JSON
### Issue Summary

Evidently we're trying to hand-render JSON rather than create an object and use `JSON.stringify()` on it, which is not kosher:
https://github.com/TryGhost/gatsby-starter-ghost/blob/master/src/components/common/meta/ArticleMeta.js#L75-L112

This results, of course, in broken JSON.

For example:
image (2)

On the left side, is Ghost's front-end, which correctly uses `JSON.stringify()`. On the right, is the same post in this Gatsby starter project, which has broken JSON as you can see.

This is how the Ghost front-end does it, using real objects:
https://github.com/TryGhost/Ghost/blob/master/core/frontend/meta/schema.js#L66-L106

### PR DESCRIPTION
**Pull request by paulmelnikow**
Stringifying JSON is much more reliable than hand-assembling it. It's also easier to read and maintain.

`JSON.stringify({foo: undefined})` is `'{}'` so there's no problem dealing with the conditional includes this way.

Fix #89

### CODE REVIEW

File: src/components/common/meta/ArticleMeta.js [hunk 1]
```diff
@@ -72,44 +109,7 @@ const ArticleMetaGhost = ({ data, settings, canonical }) => {
...
                 {settings.twitter && <meta name="twitter:site" content={`https://twitter.com/${settings.twitter.replace(/^@/, ``)}/`} />}
                 {settings.twitter && <meta name="twitter:creator" content={settings.twitter} />}
-                <script type="application/ld+json">{`
-                    {
-                        "@context": "https://schema.org/",
-                        "@type": "Article",
-                        "author": {
-                            "@type": "Person",
-                            "name": "${author.name}",
-                            ${author.image ? author.sameAsArray ? `"image": "${author.image}",` : `"image": "${author.image}"` : ``}
```
Comment (paulmelnikow) [inline src/components/common/meta/ArticleMeta.js]: This conditional doesn't make a lot of sense. Why is `sameAsArray` being checked here? Is there some logic related to `sameAs` which is missing?

Comment (AileenCGN) [reply src/components/common/meta/ArticleMeta.js]: The difference is simply the `,` which has to be appended when `author.sameAsArray` is populated and will follow after. In case it's not populated, the `author.image` property will be the last property in this object.

Comment (AileenCGN) [reply src/components/common/meta/ArticleMeta.js]: This had be done **after** it provenly failed in the [Google Structured Data testing tool](https://search.google.com/structured-data/testing-tool/u/0/)

Comment (paulmelnikow) [reply src/components/common/meta/ArticleMeta.js]: Ahh I see, that just goes away now.

Comment (AileenCGN) [reply src/components/common/meta/ArticleMeta.js]: Exactly! Much cleaner now 😺
